apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring
  namespace: spring
spec:
  destination:
    namespace: spring
    server: https://kubernetes.default.svc
  project: spring
  source:
    kustomize:
      namespace: spring
    path: kustomize/overlays/dev
    repoURL: https://github.com/redhat-developer-hub-kaito-ii-dev-apps/spring
    targetRevision: HEAD
